services:
  sma-db:
    container_name: postgres-sma
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - sma-db:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - sma-network
    restart: unless-stopped

  backend-api:
    image: chrzanekk/sma-backend-api:latest
    container_name: sma-backend-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_JWTSECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - sma-network
    depends_on:
      - sma-db
    restart: unless-stopped

#  sma-frontend-react:
#    image: chrzanekk/sma-frontend-react:latest
#    container_name: sma-frontend-react
#    ports:
#      - "5173:80"
#    depends_on:
#      - sma-backend-api
#    networks:
#      - sma-network
#    restart: unless-stopped

networks:
  sma-network:
    name: sma-network
    driver: bridge

volumes:
  sma-db: