#todo add application-docker.yml for docker build
server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: jdbc:postgresql://localhost:5444/sma
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
  thymeleaf:
      cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB
  config:
    import: "optional:file:../sma-project/.env[.properties]"

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 28800000
#  jwtExpirationMs: 60000
  tokenValidityTimeInMinutes: 15

platform:
  url: http://localhost:5173
  replyToEmail: scaffapp@kchrzanowski.pl
  fromEmail: Scaffolding App / LocalHost <scaffapp@kchrzanowski.pl>