server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5444/sma}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
  thymeleaf:
      cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB
  config:
    import: "optional:file:.env[.properties]"

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000
  tokenValidityTimeInMinutes: 15

platform:
  url: http://localhost:4200
  replyToEmail: scaffapp@kchrzanowski.pl
  fromEmail: Scaffolding App / LocalHost <scaffapp@kchrzanowski.pl>
