package pl.com.chrzanowski.sma.common.enumeration;

import lombok.Getter;

@Getter
public enum Country {
    AFGHANISTAN("AF", "Afganistan"),
    ALBANIA("AL", "Albania"),
    ALGERIA("DZ", "Algieria"),
    ANDORRA("AD", "Andora"),
    ANGOLA("AO", "Angola"),
    ARGENTINA("AR", "Argentyna"),
    ARMENIA("AM", "Armenia"),
    AUSTRALIA("AU", "Australia"),
    AUSTRIA("AT", "Austria"),
    AZERBAIJAN("AZ", "Azerbejdżan"),
    BAHAMAS("BS", "Bahamy"),
    BAHRAIN("BH", "Bahrajn"),
    BANGLADESH("BD", "Bangladesz"),
    BELARUS("BY", "Białoruś"),
    BELGIUM("BE", "Belgia"),
    BELIZE("BZ", "Belize"),
    BENIN("BJ", "Benin"),
    BHUTAN("BT", "Bhutan"),
    BOLIVIA("BO", "Boliwia"),
    BOSNIA_AND_HERZEGOVINA("BA", "Bośnia i Hercegowina"),
    BOTSWANA("BW", "Botswana"),
    BRAZIL("BR", "Brazylia"),
    BULGARIA("BG", "Bułgaria"),
    BURKINA_FASO("BF", "Burkina Faso"),
    BURUNDI("BI", "Burundi"),
    CAMBODIA("KH", "Kambodża"),
    CAMEROON("CM", "Kamerun"),
    CANADA("CA", "Kanada"),
    CAPE_VERDE("CV", "Republika Zielonego Przylądka"),
    CHAD("TD", "Czad"),
    CHILE("CL", "Chile"),
    CHINA("CN", "Chiny"),
    COLOMBIA("CO", "Kolumbia"),
    CONGO_DR("CD", "Kongo (DR)"),
    CONGO("CG", "Kongo"),
    COSTA_RICA("CR", "Kostaryka"),
    CROATIA("HR", "Chorwacja"),
    CUBA("CU", "Kuba"),
    CYPRUS("CY", "Cypr"),
    CZECH_REPUBLIC("CZ", "Czechy"),
    DENMARK("DK", "Dania"),
    DOMINICAN_REPUBLIC("DO", "Dominikana"),
    ECUADOR("EC", "Ekwador"),
    EGYPT("EG", "Egipt"),
    EL_SALVADOR("SV", "Salwador"),
    ESTONIA("EE", "Estonia"),
    ETHIOPIA("ET", "Etiopia"),
    FINLAND("FI", "Finlandia"),
    FRANCE("FR", "Francja"),
    GABON("GA", "Gabon"),
    GEORGIA("GE", "Gruzja"),
    GERMANY("DE", "Niemcy"),
    GHANA("GH", "Ghana"),
    GREECE("GR", "Grecja"),
    GUATEMALA("GT", "Gwatemala"),
    HUNGARY("HU", "Węgry"),
    ICELAND("IS", "Islandia"),
    INDIA("IN", "Indie"),
    INDONESIA("ID", "Indonezja"),
    IRAN("IR", "Iran"),
    IRAQ("IQ", "Irak"),
    IRELAND("IE", "Irlandia"),
    ISRAEL("IL", "Izrael"),
    ITALY("IT", "Włochy"),
    JAMAICA("JM", "Jamajka"),
    JAPAN("JP", "Japonia"),
    JORDAN("JO", "Jordania"),
    KAZAKHSTAN("KZ", "Kazachstan"),
    KENYA("KE", "Kenia"),
    KOREA_SOUTH("KR", "Korea Południowa"),
    KUWAIT("KW", "Kuwejt"),
    LATVIA("LV", "Łotwa"),
    LEBANON("LB", "Liban"),
    LIBERIA("LR", "Liberia"),
    LITHUANIA("LT", "Litwa"),
    LUXEMBOURG("LU", "Luksemburg"),
    MADAGASCAR("MG", "Madagaskar"),
    MALAWI("MW", "Malawi"),
    MALAYSIA("MY", "Malezja"),
    MALDIVES("MV", "Malediwy"),
    MALI("ML", "Mali"),
    MALTA("MT", "Malta"),
    MEXICO("MX", "Meksyk"),
    MOLDOVA("MD", "Mołdawia"),
    MONACO("MC", "Monako"),
    MONGOLIA("MN", "Mongolia"),
    MONTENEGRO("ME", "Czarnogóra"),
    MOROCCO("MA", "Maroko"),
    MOZAMBIQUE("MZ", "Mozambik"),
    NAMIBIA("NA", "Namibia"),
    NEPAL("NP", "Nepal"),
    NETHERLANDS("NL", "Holandia"),
    NEW_ZEALAND("NZ", "Nowa Zelandia"),
    NICARAGUA("NI", "Nikaragua"),
    NIGER("NE", "Niger"),
    NIGERIA("NG", "Nigeria"),
    NORTH_MACEDONIA("MK", "Macedonia Północna"),
    NORWAY("NO", "Norwegia"),
    OMAN("OM", "Oman"),
    PAKISTAN("PK", "Pakistan"),
    PANAMA("PA", "Panama"),
    PARAGUAY("PY", "Paragwaj"),
    PERU("PE", "Peru"),
    PHILIPPINES("PH", "Filipiny"),
    POLAND("PL", "Polska"),
    PORTUGAL("PT", "Portugalia"),
    QATAR("QA", "Katar"),
    ROMANIA("RO", "Rumunia"),
    RUSSIA("RU", "Rosja"),
    RWANDA("RW", "Rwanda"),
    SAUDI_ARABIA("SA", "Arabia Saudyjska"),
    SERBIA("RS", "Serbia"),
    SINGAPORE("SG", "Singapur"),
    SLOVAKIA("SK", "Słowacja"),
    SLOVENIA("SI", "Słowenia"),
    SOUTH_AFRICA("ZA", "RPA"),
    SPAIN("ES", "Hiszpania"),
    SRI_LANKA("LK", "Sri Lanka"),
    SWEDEN("SE", "Szwecja"),
    SWITZERLAND("CH", "Szwajcaria"),
    SYRIA("SY", "Syria"),
    TAIWAN("TW", "Tajwan"),
    TAJIKISTAN("TJ", "Tadżykistan"),
    TANZANIA("TZ", "Tanzania"),
    THAILAND("TH", "Tajlandia"),
    TUNISIA("TN", "Tunezja"),
    TURKEY("TR", "Turcja"),
    UGANDA("UG", "Uganda"),
    UKRAINE("UA", "Ukraina"),
    UNITED_ARAB_EMIRATES("AE", "Zjednoczone Emiraty Arabskie"),
    UNITED_KINGDOM("GB", "Wielka Brytania"),
    UNITED_STATES("US", "Stany Zjednoczone"),
    URUGUAY("UY", "Urugwaj"),
    UZBEKISTAN("UZ", "Uzbekistan"),
    VENEZUELA("VE", "Wenezuela"),
    VIETNAM("VN", "Wietnam"),
    YEMEN("YE", "Jemen"),
    ZAMBIA("ZM", "Zambia"),
    ZIMBABWE("ZW", "Zimbabwe");

    private final String code;
    private final String name;

    Country(String code, String name) {
        this.code = code;
        this.name = name;
    }

    public static Country fromCode(String code) {
        for (Country country : values()) {
            if (country.getCode().equalsIgnoreCase(code)) {
                return country;
            }
        }
        throw new IllegalArgumentException("Unknown country code: " + code);
    }
}
