server:
  port: ${HOST_PORT}

spring:
  datasource:
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    url: jdbc:mysql://188.68.236.142:3306/smc_db_dev?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw
    max-active: 16
    max-idle: 2
    min-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
        show-sql: true
  profiles:
    active: dev

  mail:
    host: ${PROD_EMAIL_HOST}
    port: ${PROD_EMAIL_PORT}
    username: ${PROD_EMAIL_SEND_LOGIN}
    password: ${PROD_EMAIL_SEND_PASSWORD}
    protocol: smtp
  thymeleaf:
      cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB


scaffolding-app:
  jwtSecret: 4jE4XcimwrEF9PUiOGaasXROjlw9zpkj5Hr59gojyiE6SMcxDBf9sJu/sCX/eazVrd+TyfYB/e8mz0NmgzuMNYmeb/Cw4aI1wOVgihSrVxT9erUXQXaGD8chY4wdWI9yaZOQKOdHcq8HTLYde3Xum34hgIMG3UJfHIfUNfL0a8Z6YiZGnuEnZrCsmMPTufN0o+pWQk5e7NI7fAgveTBvcV04oLJKK5sjky8a3N9rVPX2XZ6UOsG2n7Cvn/940dpy+DqRPBYCfagUyKNmakjAV2Desn7FkZ7dlGgsZGaWvXm3dhQ1l9TSdZTyx6QlLyaLB95pCDojfwaCYwKTEmj6
  jwtExpirationMs: 86400000



company:
  name: Test Company
  addressFirstLine: 00-000 Internet
  addressSecondLine: www street 12
  country: Web
  nip: 0000000000
  regon: 000000000
  pageUrl: ${PROD_PLATFORM_DOMAIN_WITH_HTTP}
  contactMail: ${PROD_ADMIN_EMAIL_CONTACT}
  contactMailto: mailto:${PROD_ADMIN_EMAIL_CONTACT}

platform:
  url: ${PROD_PLATFORM_IP_WITH_HTTP}
  name:
    front: Scaffolding App
    panel: Scaffolding App
  replyToEmail: ${PROD_EMAIL_SEND_LOGIN}
  fromEmail: Scaffolding App / <${PROD_EMAIL_SEND_LOGIN}>
tokenValidityTimeInMinutes: 15
logo:
  frontPath: /img/logos/logorch-1-128.png
  panelPath: /img/logos/logorch-1-128.png
faviconPath: /img/logos/logorch-1-128.png


